# Generated by Django 4.2.20 on 2025-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_alter_product_price_alter_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
