# Generated by Django 4.2.20 on 2025-04-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0003_alter_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
